POST  http://localhost:3000/reports
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5vcm1hbEBnbWFpbC5jb20iLCJpZCI6MSwiaWF0IjoxNjYyMDUyMDIwLCJleHAiOjE2NjIwNTU2MjB9.c7rUFOoh0z_o0TY1JSFzSujA_71jNhCHO8tGXKi1dkA

{
    "maker": "birla",
    "model": "df3",
    "year": 2013,
    "mileage": 5600,
    "lng":1.54,
    "lat":-2.45,
    "price": 2500
}


### Get report of this current user
GET http://localhost:3000/reports/
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5vcm1hbEBnbWFpbC5jb20iLCJpZCI6MSwiaWF0IjoxNjYyMDUxNTA2LCJleHAiOjE2NjIwNTUxMDZ9.NcEwZxZI4XO54FitAv4dUwGm63osH-5cRYVLwY6CbQM

GET http://localhost:3000/reports?make=Toyota&model=ttr5&year=1995
content-type: application/json
Authorization: Bearer


### approve reports
PATCH http://localhost:3000/reports/1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5vcm1hbEBnbWFpbC5jb20iLCJpZCI6MSwiaWF0IjoxNjYyMDUyMDIwLCJleHAiOjE2NjIwNTU2MjB9.c7rUFOoh0z_o0TY1JSFzSujA_71jNhCHO8tGXKi1dkA



{
    "approve": false
}

