POST http://localhost:3000/auth/signup
content-type: application/json

{
    "email": "abcf@example3.com",
    "password": "erererererer"
}


### Get user
GET http://localhost:3000/auth/3
content-type: application/json


### Find users with `email`
GET http://localhost:3000/auth
content-type: application/json

### Update user
PATCH http://localhost:3000/auth/3
content-type: application/json

{
    "email": "updated@example3.com"
}

### Delete user with id
DELETE http://localhost:3000/auth/100
content-type: application/json
